### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DeadlyDream24** [Team-VoW/WynncraftVoiceProject#12]
Missing or incorrect lines
When i have the ability to 'shift' to continue the dialogue sometimes they just continue the dialogue but im still not pressed 'shift'
(and if its countinues dialogue they speak to fast or slow e.g:Seaskipper dialogues)
Sometimes the actors say different than what is written

**Comment by kmaxii** [comment]
Seaskipper dialogues don't have any option to shift because they need to be fast as the dialogue goes way to fast.

Some quests have not been fully cut yet, so they continue, but most have been cut.

If there are any major differences in dialogue let us know about the specefics.

**Comment by DeadlyDream24** [comment]
I know Seaskipper dialogues cant be shift-ed (im not...)I said they go fast or even trough the shiftable dialogues, or slow(but this is rare) or somehow the Seaskipper dialogues (the written one)can be slower to match with the talking.
Im over that lvl when the misstalk occured and i dont remember what thes say exactly but clearly the written dialogue didnt match what they said, but i remember one: WynnExcavation Site C when i talk to Amadel he (the actor)skips in between when i dialogue 5 (or something) he allready finished-"The crystal is in the cave just inside the volcano past the base. Hurry, they are all off duty at the moment, the cave to the heart of the volcano is clear. Act swiftly, and good luck."and he talks in a nutshell (written like 3-4 sentence he says 1)
Some dialogues missing or didnt start to speak e.g: Realm of Light 2:Taproot- in the taproot.
And the skipping without me pressing shift in shiftable dialogues are occured more then just one e.g: Memory Paranoia,Creeper Infiltration,Death Whistle 
And when I enter a Dungeon they sometimes speak or not or they say one dialogue and that's all

P.S
Great mod btw, hear them talk made me laugh or cry sometimes and helps with the immersion.

**Comment by DeadlyDream24** [comment]
"And the skipping without me pressing shift in shiftable dialogues are occured more then just one e.g: Memory Paranoia,Creeper Infiltration,Death Whistle"
This has 2 examples: 1.The written dialogue is in still 1 but the speaking countinue without me pressing shift
2. (I just noticed now doing the Hollow Serenity quest, probably happened before but didnt noticed) In long dialogues in the middle of speaking the dialogue self shift itself and cuts the dialogue and countinues to the next dialogue
