### ISSUE TITLE
Incorrect Voice Line: Elemantal Excecise

### ISSUE THREAD

**Issue by GhostIsBeHere** [Team-VoW/WynncraftVoiceProject#18]
In the quest "Elemental Exercise", when you first enter the elemental training room, Captain Ragon's 4th voice line is incorrect.

Not sure if I'm supposed to put there here or somewhere else, please correct me if I messed up :]

**Comment by ShadyMedic** [comment]
Hi there, thank you for your report.

Can you please provide more details about what exactly means "incorrect line"?

We usually collect content-related reports on our Discord server (invitation link is on our website), but issues here on GitHub are fine as well.

**Comment by GhostIsBeHere** [comment]
The voicelines do not match up with the text spoken

**Comment by ShadyMedic** [comment]
Alright, so the sound plays, but on an incorrect line.

Would you remember if the voice line was shifted (the text message saying the same thing came, but sooner/later in the dialogue), or was it just the single line being changed. And if the latter, was it something significant, or it was the same thing with a different syntax or a changed word?

**Comment by GhostIsBeHere** [comment]
It said something completely different if I'm remembering right. I don't remember if it was something from that chain of dialogue but I don't think so.

**Comment by ShadyMedic** [comment]
Alright, thank you once again, we'll take a look at it.
