### ISSUE TITLE
Voices echo

### ISSUE THREAD

**Issue by Buttsaggington69** [Team-VoW/WynncraftVoiceProject#9]
i wasnt sure if there was a way to fix this but it sounds like the charcters are in a cave

**Comment by ShadyMedic** [comment]
Does this apply to any specific voicelines?

**Comment by kmaxii** [comment]
We have recently started adding reverb to lines that are in caves. If it is not in a cave it's probably some other mod causing it such as dynamic sound filters. Are you using that mod?

**Comment by Buttsaggington69** [comment]
Its in some of the bigger canyons like near almuj and the bantisu air temple

**Comment by kmaxii** [comment]
That makes sense as that mod triggeres because it's like being in a cave. But yeah, nothing to do with voices of wnn.

**Comment by Buttsaggington69** [comment]
is there not some way to change that or turn it off it kinda breaks
immersion in places where it doesn't seem right so i'd rather have it be off

**Comment by kmaxii** [comment]
Again, nothing to do with voices of wynn. Maybe there is some toggle for the reverb mod that you are using but I don't know which one you are. Otherwise, if you don't like reberb you could just delete that mod.
